class ColdfireMlxServer < Formula
  include Language::Python::Virtualenv

  desc "License-clean MLX-LM inference server with OpenAI-compatible API"
  homepage "https://github.com/getcoldfire/mlx-openai-server"
  url "https://github.com/getcoldfire/mlx-openai-server/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "2edd408fec8503722ebed60270300e97c319b305a461fc9771b60207a9ee3b3d"
  license "MIT"

  depends_on arch: :arm64
  depends_on macos: :ventura
  depends_on "python@3.12"

  # NOTICES.txt is generated per release by tools/generate_notices.sh and
  # attached to the GitHub Release as a separate asset. We fetch it here
  # and install it into share/doc/ so `coldfire-mlx-server --licenses`
  # can find it via the Homebrew Cellar layout (see app/cli.py:
  # _candidate_notices_paths).
  resource "notices" do
    url "https://github.com/getcoldfire/mlx-openai-server/releases/download/v0.1.0/NOTICES.txt"
    sha256 "ca644da3f072603b6cdca870ef8862aeaac32138c46697175fed4ddc0c3e133c"
  end

  # We deliberately do NOT enumerate dependencies as `resource` blocks
  # here. Three runtime deps (mlx, mlx-metal, torch) are wheel-only on
  # PyPI — they have no sdist for virtualenv_install_with_resources to
  # build from. Installing via `pip install -r requirements.lock` lets
  # pip resolve wheels natively, which is the only path that works for
  # Apple Silicon MLX builds.
  #
  # requirements.lock is generated by pip-compile (Phase 8a) and is
  # bundled inside the source tarball, so the install step below uses
  # the in-tree copy for hermetic version pinning.

  def install
    # Create the venv at libexec. We bypass the standard
    # virtualenv_install_with_resources path because three runtime
    # deps (mlx, mlx-metal, torch) are wheel-only on PyPI and have no
    # sdists for that pipeline to consume.
    virtualenv_create(libexec, "python3.12")

    # Homebrew's virtualenv_create runs with --without-pip; bootstrap
    # pip so we can drive the install ourselves from requirements.lock.
    system libexec/"bin/python", "-m", "ensurepip"
    system libexec/"bin/python", "-m", "pip", "install", "--upgrade",
           "--no-cache-dir", "pip"

    # Install pinned runtime deps from the in-tarball lock file. This
    # mirrors the environment the pip-licenses audit signs off on per
    # release (Phase 8b CI / Phase 8a Makefile).
    system libexec/"bin/pip", "install", "--no-cache-dir",
           "-r", buildpath/"requirements.lock"

    # Install the package itself without re-resolving deps (already
    # pinned above). --no-deps keeps the resolved versions intact.
    system libexec/"bin/pip", "install", "--no-cache-dir", "--no-deps", buildpath

    # Wire up the console script on PATH. The package's [project.scripts]
    # entry installs at <libexec>/bin/coldfire-mlx-server.
    bin.install_symlink Dir[libexec/"bin/coldfire-mlx-server"]

    # Install NOTICES.txt into share/doc/coldfire-mlx-server/ so the
    # CLI's --licenses flag can find it (see app/cli.py).
    resource("notices").stage do
      (share/"doc/coldfire-mlx-server").install "NOTICES.txt"
    end
  end

  test do
    # `--help` is the cheapest end-to-end check — it imports the full
    # app.cli module, which transitively imports parsers and validates
    # all runtime deps are importable. If a wheel-only dep (mlx,
    # mlx-metal, torch) failed to install, this test would crash.
    assert_match "coldfire-mlx-server",
                 shell_output("#{bin}/coldfire-mlx-server --help")

    # `--version` is a fast smoke that the package version matches the
    # tag we built from.
    assert_match version.to_s,
                 shell_output("#{bin}/coldfire-mlx-server --version")
  end
end
