class ColdfireInferenceServer < Formula
  include Language::Python::Virtualenv

  desc "License-clean Apple Silicon inference server with OpenAI-compatible API"
  homepage "https://github.com/getcoldfire/inference-server"
  url "https://github.com/getcoldfire/inference-server/archive/refs/tags/v0.4.4.tar.gz"
  sha256 "15dabcb388067d5074bed9184fe9eb4182fbb8f40f5f0b316caec180f65bc39d"
  license "MIT"

  depends_on arch: :arm64
  depends_on macos: :ventura
  depends_on "python@3.12"

  # NOTICES.txt is generated per release by tools/generate_notices.sh and
  # attached to the GitHub Release as a separate asset. We fetch it here
  # and install it into share/doc/ so `coldfire-inference-server --licenses`
  # can find it via the Homebrew Cellar layout (see app/cli.py:
  # _candidate_notices_paths).
  resource "notices" do
    url "https://github.com/getcoldfire/inference-server/releases/download/v0.4.4/NOTICES.txt"
    sha256 "f45cb1b5ed5040146bd3d0d781dc8d57bbf9b1062cf178fefe55cb01585e0ce7"
  end

  # We deliberately do NOT enumerate dependencies as `resource` blocks
  # here. Three runtime deps (mlx, mlx-metal, torch) are wheel-only on
  # PyPI — they have no sdist for virtualenv_install_with_resources to
  # build from. Installing via `pip install -r requirements.lock` lets
  # pip resolve wheels natively, which is the only path that works for
  # Apple Silicon MLX builds.
  #
  # requirements.lock is generated by pip-compile (Phase 8a) and is
  # bundled inside the source tarball, so the install step below uses
  # the in-tree copy for hermetic version pinning.

  def install
    # Create the venv at libexec. We bypass the standard
    # virtualenv_install_with_resources path because three runtime
    # deps (mlx, mlx-metal, torch) are wheel-only on PyPI and have no
    # sdists for that pipeline to consume.
    virtualenv_create(libexec, "python3.12")

    # Homebrew's virtualenv_create runs with --without-pip AND
    # --system-site-packages. The latter exposes the system python's
    # pip via site-packages, which makes `python -m ensurepip` skip
    # installing a venv-local bin/pip ("Requirement already satisfied").
    # `--upgrade` forces ensurepip to drop a pip wheel into the venv
    # regardless. Without it, every subsequent `bin/pip` invocation
    # fails with "Failed to execute" because the file doesn't exist.
    system libexec/"bin/python", "-m", "ensurepip", "--upgrade"

    # Drive all pip calls through `python -m pip` rather than the
    # bin/pip shim. The shim is fragile when --system-site-packages is
    # on (see above); `python -m pip` always resolves to the venv's
    # pip module regardless of where the shim ended up.
    system libexec/"bin/python", "-m", "pip", "install", "--upgrade",
           "--no-cache-dir", "pip"

    # Install pinned runtime deps from the in-tarball lock file. This
    # mirrors the environment the pip-licenses audit signs off on per
    # release (Phase 8b CI / Phase 8a Makefile).
    system libexec/"bin/python", "-m", "pip", "install", "--no-cache-dir",
           "-r", buildpath/"requirements.lock"

    # Install the package itself without re-resolving deps (already
    # pinned above). --no-deps keeps the resolved versions intact.
    system libexec/"bin/python", "-m", "pip", "install", "--no-cache-dir",
           "--no-deps", buildpath

    # Wire up the console script on PATH. The package's [project.scripts]
    # entry installs at <libexec>/bin/coldfire-inference-server.
    bin.install_symlink Dir[libexec/"bin/coldfire-inference-server"]

    # Install NOTICES.txt into share/doc/coldfire-inference-server/ so the
    # CLI's --licenses flag can find it (see app/cli.py).
    resource("notices").stage do
      (share/"doc/coldfire-inference-server").install "NOTICES.txt"
    end
  end

  test do
    # `--help` is the cheapest end-to-end check — it imports the full
    # app.cli module, which transitively imports parsers and validates
    # all runtime deps are importable. If a wheel-only dep (mlx,
    # mlx-metal, torch) failed to install, this test would crash.
    assert_match "coldfire-inference-server",
                 shell_output("#{bin}/coldfire-inference-server --help")

    # `--version` is a fast smoke that the package version matches the
    # tag we built from.
    assert_match version.to_s,
                 shell_output("#{bin}/coldfire-inference-server --version")
  end
end
